substitutions:
  name: jp-jukebox-1
  friendly_name: JP Jukebox 1
  static_ip: 192.168.1.11
  startup_sound_file: Home_Connected_Male

packages:
  device:
    url: https://github.com/skennedy/jp-jukebox.git
    ref: main
    refresh: 0s
    files:
      - path: jp-jukebox.yaml
      - path: packages/minirig.yaml
        vars:
          minirig_id: minirig
          minirig_name: "Minirig"
          minirig_mac: "AA:BB:CC:DD:EE:FF"

interval:
  - interval: 30m
    then:
      - script.execute: poll_minirig
      - script.wait: poll_minirig