substitutions:
  name: jp-jukebox-2
  friendly_name: JP Jukebox 2
  static_ip: 192.168.1.12
  startup_sound_file: Home_Connected_Male

packages:
  device:
    url: https://github.com/skennedy/jp-jukebox.git
    ref: main
    refresh: 0s
    files:
      - path: jp-jukebox.yaml
      - path: packages/minirig-battery.yaml
        vars:
          minirig_id: minirig_left
          minirig_name: "Minirig Left"
          minirig_mac: "AA:BB:CC:DD:EE:FF"
      - path: packages/minirig-battery.yaml
        vars:
          minirig_id: minirig_right
          minirig_name: "Minirig Right"
          minirig_mac: "11:22:33:44:55:66"

interval:
  - interval: 30m
    then:
      - script.execute: poll_minirig_left
      - script.wait: poll_minirig_left
      - script.execute: poll_minirig_right
      - script.wait: poll_minirig_right